name: ext_pretrain_ser
channels:
    - conda-forge
    - anaconda
dependencies:
    - python=3.9.16
    - numpy=1.23.1
    - ffmpeg<7
    - pip=22.3.1
    - pip:
      - https://download.pytorch.org/whl/cu118/torch-2.1.1%2Bcu118-cp39-cp39-linux_x86_64.whl
      - facenet-pytorch==2.5.3
      - ffmpeg-python==0.2.0
      - ffprobe-python==1.0.3
      - fqdn==1.5.1
      - ftfy==6.1.3
      - ipywidgets==8.1.1
      - isoduration==20.11.0
      - jsonpointer==2.4
      - matplotlib==3.8.2
      - notebook==7.0.6
      - opencv-python==4.8.1.78
      - pandas==2.1.3
      - pip-chill==1.0.1
      - plotly==5.18.0
      - timm==0.4.5
      - transformers==4.35.2
      - umap-learn==0.5.5
      - uri-template==1.3.0
      - webcolors==1.13
      - webdataset==0.2.79
      - wandb==0.16.1
      - torchinfo==1.8.0
      - torch-yin==0.1.3
      - librosa
      - torchmetrics


# use numba==0.54.0
# use numpy 1.20.3
# /root/miniconda/envs/depmbt/lib/python3.9/site-packages/timm/layers/pos_embed.py 
# Change line 42 to 
# posemb = F.interpolate(posemb, size=new_size, mode=interpolation, align_corners=True)
# 
